name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted  #if you want own host so give self hosted 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

     
      - name: go to clone directory
        run: cd /home/ubuntu/react_code_swigo    #give your actual path of your local repo 
        
      - name: install all recuriments
        run: npm install

      - name: run our application 
        run : npm run dev 
